### ISSUE TITLE
Xiaomi Mi 11 uses LP header version 10.3

### ISSUE THREAD

**Issue by dylangerdaly** [unix3dgforce/lpunpack#1]
```
Traceback (most recent call last):
  File "/home/user/Apps/lpunpack/lpunpack.py", line 443, in <module>
    LpUnpack(**vars(namespace)).unpack()
  File "/home/user/Apps/lpunpack/lpunpack.py", line 377, in unpack
    metadata = self.ReadMetadata()
  File "/home/user/Apps/lpunpack/lpunpack.py", line 325, in ReadMetadata
    group.name = str(group.name, 'utf-8').strip('\x00')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf0 in position 8: invalid continuation byte
```

It's failing to read the group names because the offsets have been updated.

**Comment by unix3dgforce** [comment]
> 
> 
> ```
> Traceback (most recent call last):
>   File "/home/user/Apps/lpunpack/lpunpack.py", line 443, in <module>
>     LpUnpack(**vars(namespace)).unpack()
>   File "/home/user/Apps/lpunpack/lpunpack.py", line 377, in unpack
>     metadata = self.ReadMetadata()
>   File "/home/user/Apps/lpunpack/lpunpack.py", line 325, in ReadMetadata
>     group.name = str(group.name, 'utf-8').strip('\x00')
> UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf0 in position 8: invalid continuation byte
> ```
> 
> It's failing to read the group names because the offsets have been updated.

Thanks for the feedback. The utility file has been updated. Added support for header version 1.2. found and fixed other bugs. 

Test was carried out on firmware venus_images_V12.0.19.0.RKBCNXM_20210122.0000.00_11.0_cn
