### ISSUE TITLE
Can't start: TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by csdvrx** [unix3dgforce/lpunpack#3]
$ python3 lpunpack/lpunpack.py -h
Traceback (most recent call last):
  File "lpunpack/lpunpack.py", line 183, in <module>
    class UnpackJob:
  File "lpunpack/lpunpack.py", line 186, in UnpackJob
    parts: list[tuple[int, int]] = field(default_factory=list)
TypeError: 'type' object is not subscriptable

**Comment by unix3dgforce** [comment]
Please specify python version?

**Comment by unix3dgforce** [comment]
Please specify python version?
