### ISSUE TITLE
Small Info

### ISSUE THREAD

**Issue by HemanthJabalpuri** [unix3dgforce/lpunpack#4]
@unix3dgforce 
LpMetadataPartition, LpMetadataExtent, LpMetadataPartitionGroup and LpMetadataBlockDevice are read from BackupMetadata instead from PrimaryMetadata.
https://github.com/unix3dgforce/lpunpack/blob/0d33cfac2102324ceee90e86b734d27046697123/lpunpack.py#L306
https://github.com/unix3dgforce/lpunpack/blob/0d33cfac2102324ceee90e86b734d27046697123/lpunpack.py#L330
Is this intentional?

Thanks

**Comment by unix3dgforce** [comment]
Hi,
In what form would you like to see the information in plain text or in json format

**Comment by unix3dgforce** [comment]
If the super.img is generated correctly. PrimaryMetadata is consistent with BackupMetadata

**Comment by unix3dgforce** [comment]
The presence of BackupMetada in the super.img image ensures that PrimaryMetadata is consistent with BackupMetada, since the file pointer passed to the WriteMetadata static method is used when writing both PrimaryMetadata and BackupMetada
